### ISSUE TITLE
keep-input-values executes other directives twice

### ISSUE THREAD

**Issue by amosrivera** [platanus/angular-keep-values#12]
The use of $compile inside keep-input-values makes angular execute other directives twice. 
```
.replaceWith($compile(checkElement)(scope));
```

Example case: http://jsfiddle.net/g69bx9ao/5/

We can use the preCompile state to add attributes before angular has compiled the form elements.

```
var directive = {
  compile: compile,
  restrict: 'A'
};

function compile(){
 // add attributes to elements here

  return {
    pre: preCompile
  };
}
```
PR: https://github.com/platanus/angular-keep-values/pull/13

**Comment by ReneMoraales** [comment]
Merged.
